### ISSUE TITLE
Create a simple docker-based data migration system to easily import data into elasticsearch

### ISSUE THREAD

**Issue by danmelton** [hackoregon/housing-2018#2]
Once we have an elasticsearch system setup, we can quickly add new datasets. But, we'll need to figure out a way to do data 'migrations'.

It'd be great if a developer could just run docker-compose up, and, as part of the process of setting up the system, a set of scripts automatically fetch and install data items.

The process might look something like:

docker-compose up 

```
./docker-compose.yml
  services:
    setup_data:
        build: build/Dockerfile (contains all nifty little package installations we'll need in our linux image)
       volumes: ['data-migrations:data-migrations']
       cmd: '/bin/bash', '-c', 'cat /usr/local/bin/data-migration.sh | tr -d "\r" | bash'
       depends_on: ['elasticsearch']
```

Docker compose up launches elasticsearch first, and then runs the setup_data container.

setup_data container, /usr/local/bin/data-migration.sh

It loops through the data-migrations folder, parses each file name, and then checks elasticsearch to see if the migration already exists:

something like, curl elasticsearch:9200/migrations/2018housing

if it returns 404 (40-something), it runs the migration. When the migration is done, it updates the index, maybe with some metadata:
curl -XPOST elasticsearch:9200/datasets/2018housing -d '{ran: true, lastUpdate:, title: , description:, source:}'
 
Task List
- [ ] Setup a basic docker container and add to dockercompose with test migration
- [ ] Add to readme how to write a migration
